name: Sincronizar HTML con Salesforce

on:
  push:
    paths:
      - '*.html'

jobs:
  sincronizar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Establecer Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install simple-salesforce

    - name: Identificar archivos HTML modificados
      id: files
      run: |
        files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.html$')
        echo "MODIFIED_FILES<<EOF" >> $GITHUB_ENV
        echo "$files" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
    - name: Enviar HTML a Salesforce
      env:
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
        SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
        SF_CONSUMER_SECRET: ${{ secrets.SF_CONSUMER_SECRET }}
      run: |
        python send_to_sf.py $MODIFIED_FILES
