name: Sincronizar HTML con Salesforce

on:
  pull_request:
    branches:
      - main

jobs:
  sincronizar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Hace un fetch completo de todas las ramas

    - name: Establecer Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install simple-salesforce

    - name: Identificar archivos HTML modificados
      id: files
      run: |
        git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.html$' > modified_files.txt || true
        if [ ! -s modified_files.txt ]; then
          echo "No HTML files modified."
          echo "SHOULD_EXIT=true" >> $GITHUB_ENV
        fi
        
    - name: Enviar HTML a Salesforce
      if: env.SHOULD_EXIT != 'true'
      env:
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
        SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
        SF_CONSUMER_SECRET: ${{ secrets.SF_CONSUMER_SECRET }}
      run: |
        python send_to_sf.py modified_files.txt
